Empty appointments bug fix
UMCU-Digital-Health/No_Show pull request #153
Opened 2024-12-23 14:54 UTC by WoltersEric

closes #151

2025-01-06 09:19 UTC, rubenpeters91 requested changes

2025-01-06 09:19 UTC, rubenpeters91 commented on deploy.sh
> +export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
Maybe add a comment why this is neccessary and add to CHANGELOG

2025-01-06 09:19 UTC, rubenpeters91 commented on src/noshow/api/app.py
> +        logger.error("No appointments provided")
I think the cleaner option would be to raise an exception, because generally we want to be informed when the appointment list is empty, this is only expected a couple of times per year. For example:
```raise HTTPException(status_code=400, detail="Input cannot be empty.")```
 maybe best to do both logger.error and the exception

2025-01-06 13:29 UTC, WoltersEric commented
I added your suggestions. The latest version is now running on acceptance

2025-01-06 13:35 UTC, rubenpeters91 requested changes

2025-01-06 13:35 UTC, rubenpeters91 commented on src/noshow/api/app_helpers.py
> +    CLINIC_CONFIG: Dict[str, Any],
Maybe just import this from the config module? Saves another parameter

2025-01-06 13:35 UTC, rubenpeters91 commented on src/noshow/api/app_helpers.py
> +    logger: Any,
Better to create a new logger object in this module and use that

2025-01-06 13:35 UTC, rubenpeters91 commented on src/noshow/api/app_helpers.py
> +    apirequest: Any,
Type is ApiRequest

2025-01-07 09:17 UTC, rubenpeters91 approved these changes
Looks good, I think you need to change the monkeypatch for CLINIC_CONFIG, since it's also imported in app_helpers not only in app. That should fix the unit test

2025-01-08 13:24 UTC, merged